# Generated by Django 4.0.4 on 2022-05-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Title')),
                ('slug', models.TextField(blank=True, null=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articlesImage', verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('keywords', models.TextField(verbose_name='Keywords')),
                ('description', models.TextField(default='a  description', verbose_name='Description')),
                ('short_description', models.TextField(blank=True, default='a short description', null=True, verbose_name='Short description')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articles', verbose_name='Article')),
            ],
        ),
    ]
