# Generated by Django 4.0.4 on 2022-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0002_alter_sitesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
                ('youtube', models.URLField(verbose_name='Youtube')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
        ),
    ]
