# Generated by Django 4.0.4 on 2022-06-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicesusersmessages_servicesmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesmessages',
            old_name='is_seller',
            new_name='is_service',
        ),
    ]
