# Generated by Django 4.0.4 on 2022-05-30 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='userphoto/', verbose_name='User Photo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_auth', models.BooleanField(default=False, verbose_name='Phone Auth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True, verbose_name='Gender')),
                ('role', models.CharField(blank=True, choices=[('user', 'user'), ('seller', 'seller'), ('service', 'service'), ('admin', 'admin')], max_length=50, null=True, verbose_name='Rols')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Status')),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Super User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
