# Generated by Django 4.0.5 on 2022-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discounted Price'),
        ),
    ]
